name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 3: Run tests (optional)
      - name: Run tests
        run: |
          echo "No tests for this example"
      
      # Step 4: Deploy to production folder
      - name: Deploy to production folder
        run: |
          $prodPath = "C:\Users\sde2\Documents\Projects\PG Node\CICD-local\prod\my-app"
          if (Test-Path $prodPath) { Remove-Item -Recurse -Force $prodPath }
          New-Item -ItemType Directory -Force -Path $prodPath
          Copy-Item -Recurse -Force .\* $prodPath
